name: Node.js CI

on: [push]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js for front
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - run: npm ci
        working-directory: ./front
      - run: npm test
        working-directory: ./front
      - run: npm ci
        working-directory: ./back
      - run: npm test
        working-directory: ./back

  builds:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js for front
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - run: npm ci
        working-directory: ./front
      - run: npm run build --if-present
        working-directory: ./front
      - run: npm ci
        working-directory: ./back
      - run: npm run build --if-present
        working-directory: ./back

  pushback:

    needs: builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/back:latest

  pushfront:

    needs: builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/front:latest